### PR TITLE
Add Support for Comments

### LINKED ISSUE #112: Support for comments
We encountered a issue where the library fails to read the file if it finds a comment:
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at easy-template-x.js:1907:47
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:11083:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
```

Here it fails to find the body node (or the children of the body node):
```js
async getHeaderOrFooter(type) {
    var _sectionProps$childNo, _attributes;
    const nodeName = this.headerFooterNodeName(type);
    const nodeTypeAttribute = this.headerFooterType(type);

    // find the last section properties
    // see: http://officeopenxml.com/WPsection.php
    const docRoot = await this.mainDocument.xmlRoot();
    const body = docRoot.childNodes[0];
    const sectionProps = last(body.childNodes.filter(node => node.nodeType === XmlNodeType.General));
    if (sectionProps.nodeName != 'w:sectPr') return null;
```

A look into the document.xml shows the issue:
```xml
<w:document ...
    mc:Ignorable="w14 w15 wp14"><!-- Generated by Aspose.Words for .NET 23.5.0 -->
    <w:body>
        <w:p w:rsidR="001F47F4" w:rsidP="001F47F4" w14:paraId="425762CC" w14:textId="77777777">
....
```

The library tries to get the first child node as the body, but this is not always the case (e.g. there could be a comment beforehand or like in #103 a `w:background` tag).

[A file generated with the aspose.words online editor](https://products.aspose.app/words/editor) has the same problem:
[test.docx](https://github.com/alonrbar/easy-template-x/files/15429121/test.docx)

I've tried to fix it by changing the code:
```ts
private async getHeaderOrFooter(type: ContentPartType): Promise<XmlPart> {

    const nodeName = this.headerFooterNodeName(type);
    const nodeTypeAttribute = this.headerFooterType(type);

    // find the last section properties
    // see: http://officeopenxml.com/WPsection.php
    const docRoot = await this.mainDocument.xmlRoot();
    const body = docRoot.childNodes.find(node => node.nodeName == 'w:body');
    if (body == null)
        return null;

    const sectionProps = last(body.childNodes.filter(node => node.nodeType === XmlNodeType.General));
    if (sectionProps.nodeName != 'w:sectPr')
        return null;
```

This allows the library to parse the comments without a problem, but not they are detected as text nodes (I believe) and written into the final document like this:
```xml
<w:document ...
    xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"
    mc:Ignorable="w14 w15 wp14">
    <#comment/>
    <w:body>
        <w:p w:rsidR="001F47F4" w:rsidP="001F47F4" w14:paraId="425762CC" w14:textId="77777777">
...
```
Which fails to open using word as it's an invalid document.

To make a proper fix, one would probably have to add full support for comments.

### PR DESCRIPTION
**Pull request by timnieder**
Closes #112 
And also #103 (not related to the comments, but the document.body access)

### CODE REVIEW

**Comment by alonrbar** [comment]
Hi, 
First of all, thank you for your contribution :)
Had a quick look and overall looks good. Can you add tests to verify the new functionality? I'd try to review as soon as possible once those exists.

**Comment by timnieder** [comment]
Thanks for the quick response!
I added unit tests for the comments.
Not sure if I should add a comment to a docx file for a integration test or where that would fit in.

**Comment by alonrbar** [comment]
Looks great 👌
I would add an integration test but I'll merge the PR and just add it myself now.
Thanks again!

**Comment by alonrbar** [comment]
This PR is now part of v3.2.1, published just now to npm.

**Pull request merged**
