### PR TITLE
Feature/customxml

### PR DESCRIPTION
**Pull request by sebastianrogers**
Adds the ability to load and save custom XML files, which are used by Office features like data binding.

### CODE REVIEW

**Comment by alonrbar** [comment]
Hi, 
Can you point me for some more information about "custom xml files" and data binding in Word?

**Comment by sebastianrogers** [comment]
https://docs.microsoft.com/en-gb/archive/blogs/modonovan/word-2007-content-controls-and-xml-part-1-the-basics

**Comment by sebastianrogers** [comment]
Yes its that old!

**Comment by sebastianrogers** [comment]
Hi Alon

Are you happy to implement this?  Its key to how to set the values in data bound content controls.

Cheers

Sebastian

**Comment by alonrbar** [comment]
The code itself is neat and clean. But since this is only relevant for data binding and content controls I'm not sure that this belongs in the main repo. I think it's better be written in the specific package that will handle it.

You can use this code and achieve the same effect without adding the `customXmlFiles` on the Docx class. To handle loading and saving check out the idea proposed in [this comment](https://github.com/alonrbar/easy-template-x/issues/25#issuecomment-584028096).

**Comment by sebastianrogers** [comment]
Okay let me give that a try it does seem simple enough.

**Comment by alonrbar** [comment]
Closed by #28

**Pull request closed without merging**
