### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by sebastianrogers**
Provides extension support for

- Content Control
- Data Binding

### CODE REVIEW

**Comment by alonrbar** [comment]
Hi, thanks for the PR 👍
I will need some time to go through it. Hopefully in the next few days.

**Comment by sebastianrogers** [comment]
Marvellous - cheers

**Comment by sebastianrogers** [comment]
Hi There

Any thoughts?

Cheers

Sebastian

**Comment by alonrbar** [comment]
Hi,

Sorry for the delay, quite busy lately and didn't have time to properly examine the PR. 

Few quick thoughts though:

- I see the PR includes many linting changes such as single quote to double quote and indentation. This adds a lot of noise with no additional value, please avoid these kind of changes in a PR.

- From a very quick look the extensions api itself and the relevant documentations it seems pretty good.

- I hope it's not too much of a trouble for you but I was thinking that it's probably best to add only the extension api itself to this package and have a different package with the extension implementation (say etx-extension-content-controls). A reference to the extension package could then be added to the readme under "Community Extensions".

Thank and cheers :)

**Comment by sebastianrogers** [comment]
1. Linting - suspect its prettier which I use heavily.  Not a problem I can reverse these.
2. Splitting the package - good idea I'll get onto this.

Cheers

**Comment by alonrbar** [comment]
Also, I know I suggested to PR the extension but to avoid unnecessary diffs it may be better to PR the develop branch.

**Comment by sebastianrogers** [comment]
Understood – I will be able to do a new pull request based on these recommendations next week.

**Comment by sebastianrogers** [comment]
First pull request in.

Second one for wiring custom XML files to follow next week.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Sebastian Rogers
Sent: Wednesday, January 29, 2020 1:55:05 AM
To: alonrbar/easy-template-x <reply@reply.github.com>; alonrbar/easy-template-x <easy-template-x@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [alonrbar/easy-template-x] Extensions (#23)


Understood – I will be able to do a new pull request based on these recommendations next week.

**Comment by alonrbar** [comment]
Great! Will go over it today.

**Comment by alonrbar** [comment]
Closing this PR - replaced by #24.

**Pull request closed without merging**
